check if zip file was created

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,7 +26,15 @@ jobs:
         run: |
           mkdir lambda_package
           cp -r lambda/aws_lambda.py lambda_package/
-          zip -r lambda_package/lambda_package.zip lambda_package
+          zip -r lambda_package.zip lambda_package
+
+          if [ -f "lambda_package.zip" ]; then
+            echo "ZIP file created successfully."
+          else
+            echo "ZIP file creation failed."
+            exit 1  # Exit the workflow with an error code
+          fi
+          
           rm -rf lambda_package
         
   deploy_lambda:
@@ -41,7 +49,7 @@ jobs:
             --runtime python3.11 \
             --handler aws_lambda.lambda_handler \
             --role arn:aws:iam::256522976328:role/AdministratorAccess \
-            --zip-file fileb://lambda_package/lambda_package.zip
+            --zip-file fileb://lambda_package.zip
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
